# Generated by Django 3.0 on 2022-12-07 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCadastro', '0002_auto_20221206_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data_cadastro',
            field=models.DateField(auto_now=True),
        ),
    ]
