# Generated by Django 3.0 on 2022-12-07 01:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCadastro', '0003_auto_20221206_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data_cadastro',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao_produto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
